config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: 'recipes#index'
  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorite, only: %i[create destroy]
    resource :comment, only: %i[create destroy show]
    get 'like' => 'favorites#favousers', as: 'users'
  end
  post 'change_index', to: 'recipes#'
  post 'fixed_recipe', to: 'recipes#'
  post 'un_fixed_recipe', to:'recipes#'

  get 'hashtags', to: 'hashtags#show'
  get 'hashtags/:hashtag', to: 'hashtags#show', as: 'search_route'
  post 'hashtags/', to: 'hashtags#search', as: 'search_post_route'
  resources :notifications, only: :index
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  attachment :image

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  has_many :favorites, class_name: 'Favorite', dependent: :destroy
  # いいねしたユーザー一覧で使う
  has_many :favousers, through: :favorites, source: :user

  has_many :comments, class_name: 'Comment', dependent: :destroy
  # コメントしたユーザー一覧で使う
  has_many :commusers, through: :comments, source: :user

  has_many :recipehashtags, class_name: 'RecipeHashtag', dependent: :destroy
  # ハッシュタグ一覧で使う
  has_many :hashtags, through: :recipehashtags, source: :hashtag

  has_many :commenthashtags
  # 通知
  has_many :notifications, dependent: :destroy
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @display_index = session[:home_display_index]
    case @display_index
    when '0'
      @recipes = Recipe.all
    when '1'
      @recipes = Recipe.where(user: current_user.followings)
    when '2'
      # 人気レシピ
    else
      @recipes = Recipe.all
    end
    @day_ranking = HashtagCount.generate_ranking(1, Date.today, Date.today)
    @week_ranking = HashtagCount.generate_ranking(1, Date.today.ago(7.days), Date.today)
    @month_ranking = HashtagCount.generate_ranking(1, Date.today.ago(30.days), Date.today)
  end

  def change_index
    session[:home_display_index] = params[:display_index]
    redirect_to action: 'index'
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    hashtags = params[:hashtags].split(' ')
    hashtags.each do |tag|
      hashtag = Hashtag.find_or_create_by(name: tag)
      @recipe.hashtags << hashtag
      count = HashtagCount.find_or_initialize_by(hashtag: hashtag, date: Date.today)
      count.count ||= 0
      count.count += 1
      count.save
    end

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: '投稿に成功しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: '更新に成功しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipe_path
  end

  def fixed_recipe
    current_user.update(fixed_recipe_id: params[:recipe])
    redirect_back(fallback_location: root_path)
  end

  def un_fixed_recipe
    current_user.update(fixed_recipe_id: -1)
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :body, :image)
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/recipes/_form.html.slim
= form_for @recipe, id: 'form' do |f|
  p 
    = f.label :title, "レシピ名"
    = f.text_field :title

  p 
    = f.label :body, "作り方"
    = f.text_area :body,class:"input_area"

  p 
    = f.label :image, "写真"
    = f.attachment_field :image

  p 
    = f.label :hashtags, "ハッシュタグ"
    .hashtag_btn_ctrl 
      = f.button '＋', type: :button, class:'plus'
      = f.button 'ー', type: :button, class:'minus'
  p.hashtags
    = text_field_tag :hashtag, '',class:'hashtag_field'

  = hidden_field_tag 'hashtags', value: '', id: "hashtags"

  p = f.submit "登録"

javascript:
  var original = $('.hashtag_field');
  $('.plus').click(function() {
    original.clone().appendTo('.hashtags');
  });
  $('.minus').click(function() {
    $('.hashtags .hashtag_field').last().remove();
  });

  //ハッシュタグを空白区切りにしてコントローラに送信
  $('form').submit(function(event){
    let hashtags = $("[name='hashtag']");
    let values = [];
    hashtags.each(function(){
      values.push($(this).val());
    });
    console.log(values.join(' '));
    $("#hashtags").val(values.join(' '));
  });

app/views/recipes/_recipe_card.html.slim
.card
  - if isFixed
    p 固定されたレシピ
  .recipe
    .left
      = link_to user_path(recipe.user.id) do
        = attachment_image_tag recipe.user, :profile_image, fallback: "no-image.png"
    .right
      .top
        = link_to recipe.user.username, user_path(recipe.user.id), class:"user_name"
        = button_tag '・・・', type: 'button', class: 'openbtn1'
        div.recipe_edit
          ul
            - user = recipe.user
            - if current_user == user 
              li 
                = link_to "削除", recipe_path(recipe), { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } } }
              li
                - if recipe == current_user.fixed_recipe
                  = link_to "固定解除", un_fixed_recipe_path(recipe: recipe), method: :post
                - else
                  = link_to "固定する", fixed_recipe_path(recipe: recipe), method: :post
              li
                = link_to "編集する", edit_recipe_path(recipe), method: :get
            - else
              - if current_user != nil
                li 
                  - if current_user.following?(user)
                    = link_to "フォロー解除", user_relationships_path(user.id), method: :delete
                  - else
                    = link_to "フォローする", user_relationships_path(user.id), method: :post
              li
                p = "#{user.username}さんをミュート"
              li 
                p = "#{user.username}さんをブロック"
      = link_to recipe_path(recipe), class:'recipe_img' do
        = attachment_image_tag recipe, :image
      .recipe_reaction 
        = button_to recipe_comment_path(recipe.id), method: :get do 
          = image_tag ('comment.png'), class:'reaction-image'
        p.count = "#{recipe.commusers.count}"
        = button_to recipe_favorite_path(recipe.id), method: :post do
          = image_tag ('retweet_shape.png'), class:'reaction-image'
        p.count 8
        - if current_user!=nil
          -if current_user.favoriting?(recipe)
            = button_to recipe_favorite_path(recipe.id), method: :delete do
              = image_tag ('heart.png'), class:'reaction-image'
          -else
            = button_to recipe_favorite_path(recipe.id), method: :post do
              = image_tag ('heart_shape.png'), class:'reaction-image'
        -else # ログイン処理に飛ばす
          p |ログインしてください
        p.count = "#{recipe.favousers.count}"
      p.update 
        = recipe.updated_at.strftime("%Y-%m-%d %H:%M")
        | 更新 

app/views/recipes/_recipe_info.html.slim
.center_container
  h1.page_title
    | レシピ詳細
  .recipe_info_content
    .card.recipe_info_card
      = attachment_image_tag @recipe, :image
      .recipe_information
        h2 
          = @recipe.title
        .hashtags
          -@recipe.hashtags.each do |tag|
            = link_to "##{tag.name} ", search_route_path(hashtag: tag.name)
        -if(0 < @recipe.favousers.count)
          p = link_to "#{@recipe.favousers.count}件のいいね", recipe_users_path(@recipe)
        p.recipe_body_title
          | レシピ
        = simple_format @recipe.body
    .card.recipe_user_card
      = link_to user_path(@recipe.user), class:"user_name" do
        | By  
        = @recipe.user.username
      .profile = simple_format @recipe.user.profile
      = link_to user_path(@recipe.user) do
        = @recipe.user.username
        | さんのページへ 
      - if current_user != nil
        - if @recipe.user.id == current_user.id
          = link_to "編集", edit_recipe_path(@recipe), class:"recipe_edit"
  .recipe_info_comments 
    - @recipe.comments.each do |comment|
      .comment
        .profile_image 
          = link_to user_path(comment.user.id), class:"image" do
            = attachment_image_tag comment.user, :profile_image, fallback: "no-image.png"
        .comment_main
          .profile
            p.name = comment.user.username
            p.update = comment.updated_at.strftime("%Y-%m-%d")
          .body
            p = comment.body

app/views/recipes/_recipe_list.html.slim
- recipes.each do |recipe|
  == render 'recipes/recipe_card', recipe: recipe, isFixed: false

javascript:
  $(document).ready(function() {
    $(".openbtn1").on("click", function(){//ボタンがクリックされたら
      $(this).toggleClass('active');//ボタン自身に activeクラスを付与し
      $(this).siblings('.recipe_edit').toggleClass('editactive');//ナビゲーションにpanelactiveクラスを付与
      var $closepanel = $('<div>', {class: 'closepanel' });
      $(this).parent().append($closepanel);
    });
    $(document).on('click', '.closepanel, .recipe_edit li', function() {
      $(".openbtn1").removeClass('active');//ボタンの activeクラスを除去し
      $(".recipe_edit").removeClass('editactive');//ナビゲーションのpanelactiveクラスも除去
      $(".closepanel").remove();
    });
  });

app/views/recipes/edit.html.slim
h1.page_title
  | レシピ編集

- if @recipe.errors.any?
  .notification.is-danger
    h2 = pluralize(@recipe.errors.count,'error')
    ul 
      - @recipe.errors.full_messages.each do |message|
        li = message
      end 

== render 'form'

app/views/recipes/index.html.slim
div.container_recipe.center_container
  h1.page_title ホーム
  ul.tab_buttons
      li.tab
        .element
          = link_to '最新', change_index_path(display_index: 0), method: :post
      li.tab
        .element
          = link_to 'フォロー中', change_index_path(display_index: 1), method: :post
      li.tab
        .element
          = link_to '人気順', change_index_path(display_index: 2), method: :post
  .container
    -if @recipes != nil
      == render 'recipe_list', recipes: @recipes
.side-bar 
  .top-margin
  .side-element
    .recommended-recipe
      h2 おすすめレシピ
      .recommended-recipes
        - @day_ranking.each do |tag|
          .trend
            p.count = "今日のトレンド"
            p.hashtag = link_to tag.hashtag.name, search_route_path(hashtag: tag.hashtag.name)
            p.count = "#{tag.count}件の投稿"
        - @week_ranking.each do |tag|
          .trend
            p.count = "今週のトレンド"
            p.hashtag = link_to tag.hashtag.name, search_route_path(hashtag: tag.hashtag.name)
            p.count = "#{tag.count}件の投稿"
        - @month_ranking.each do |tag|
          .trend
            p.count = "今月のトレンド"
            p.hashtag = link_to tag.hashtag.name, search_route_path(hashtag: tag.hashtag.name)
            p.count = "#{tag.count}件の投稿"
    .recommended-user
      h2 おすすめユーザー
      .recommended-users
        p = link_to '気まぐれクック', recipes_path
        p = link_to '気まぐれクック', recipes_path
        p = link_to '気まぐれクック', recipes_path

javascript:
  $(function(){
    var index = "#{@display_index}";
    console.log(index);
    $('.tab').eq(index).addClass('tab_active');
    var $select_tab = $('<div>', {id: 'select_tab' });
    $('.tab_active .element').append($select_tab);

    //$('.tab').on('click',function(){
    //  $('.tab_active').removeClass('tab_active');
    //  $(this).addClass('tab_active');
    //  $('.box_show').removeClass('box_show');
    //  const index = $(this).index();
    //  $('.tabbox').eq(index).addClass('box_show');
    //  $('#select_tab').appendTo('.tab_active .element');
    //});
  });

app/views/recipes/new.html.slim
.center_container
  h1.page_title
    | 新規レシピ作成
  == render 'form'

app/views/recipes/show.html.slim
== render 'recipe_info'