config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: 'recipes#index'
  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorite, only: %i[create destroy]
    resource :comment, only: %i[create destroy show]
    get 'like' => 'favorites#favousers', as: 'users'
  end
  post 'change_index', to: 'recipes#'
  post 'fixed_recipe', to: 'recipes#'
  post 'un_fixed_recipe', to:'recipes#'

  get 'hashtags', to: 'hashtags#show'
  get 'hashtags/:hashtag', to: 'hashtags#show', as: 'search_route'
  post 'hashtags/', to: 'hashtags#search', as: 'search_post_route'
  resources :notifications, only: :index
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  # フォローするとき
  def create
    relationship = current_user.follow(params[:user_id])
    relationship.followed.create_notification_follow!(current_user)
    redirect_to request.referer
  end

  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @user = user
    @users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @user = user
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper
end

app/views/relationships/_user_list.html.slim
.users_index.center_container
  .tab_buttons
    - if followers
      = link_to 'フォロー中', user_followings_path(@user.id)
      p.select_now = 'フォロワー'
    -else
      p.select_now = 'フォロー中'
      = link_to 'フォロワー', user_followers_path(@user.id)
  .users
    - if @users.exists?
      - @users.each do |user|
        div.card_user
          = link_to user_path(user), class: 'image' do
            = attachment_image_tag user, :profile_image, fallback: 'no-image.png'
          .profile 
            = link_to user.username,  user_path(user), class:'user_name'
            p.recipe_count
              | 投稿数： 
              = user.recipes.length
          - if current_user!=nil
            - if @user.id == current_user.id
              -if current_user.following?(user)
                = button_to "フォロー解除", user_relationships_path(user.id), method: :delete
              -else
                = button_to "フォローする", user_relationships_path(user.id), method: :post
    - else
      p = nomessage

app/views/relationships/followers.html.slim
h1.page_title = "#{@user.username}のフォロワー一覧"
== render 'user_list', nomessage: 'フォロワーがいません。', followers: true

app/views/relationships/followings.html.slim
h1.page_title = "#{@user.username}のフォロー一覧"
== render 'user_list', nomessage: 'フォローしている人がいません。', followers: false