config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: 'recipes#index'
  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorite, only: %i[create destroy]
    resource :comment, only: %i[create destroy show]
    get 'like' => 'favorites#favousers', as: 'users'
  end
  post 'change_index', to: 'recipes#'
  post 'fixed_recipe', to: 'recipes#'
  post 'un_fixed_recipe', to:'recipes#'

  get 'hashtags', to: 'hashtags#show'
  get 'hashtags/:hashtag', to: 'hashtags#show', as: 'search_route'
  post 'hashtags/', to: 'hashtags#search', as: 'search_post_route'
  resources :notifications, only: :index
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :recipes, dependent: :destroy

  validates :username, presence: true

  belongs_to :fixed_recipe, class_name: 'Recipe', optional: true, foreign_key: 'fixed_recipe_id'

  has_many :favorites, class_name: 'Favorite', foreign_key: 'user_id', dependent: :destroy
  # いいねしたレシピ一覧画面で使う
  has_many :favorecipes, through: :favorites, source: :recipe

  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', dependent: :destroy
  # コメントしたレシピ一覧画面で使う
  has_many :commrecipes, through: :comments, source: :recipe

  # フォローをした、されたの関係
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  # フォローしたときの処理
  def follow(user_id)
    return relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # いいねをしたときの処理
  def favorite(recipe_id)
    return favorites.create(recipe_id: recipe_id)
  end

  # いいねを外すときの処理
  def unfavorite(recipe_id)
    favorites.find_by(recipe_id: recipe_id).destroy
  end

  def favoriting?(recipe)
    favorecipes.include?(recipe)
  end

  def comment(comment, recipe_id)
    return comments.create(body: comment, recipe_id: recipe_id)
  end

  def uncomment(comment_id)

  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes.reject { |recipe| recipe == @user.fixed_recipe }
  end

  def edit
    @user = User.find(params[:id])
    redirect_to users_path, alert: '不正なアクセスです。' if @user != current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新に成功しました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user do |f| 

  p 
    = f.label :username, "ユーザー名"
    = f.text_field :username
      
  p 
    = f.label :email, "メールアドレス"
    = f.text_field :email

  p 
    = f.label :profile, "プロフィール"
    = f.text_area :profile, class:"input_area"

  p 
    = f.label :profile_image, "プロフィール画像"
    = f.attachment_field :profile_image

  p.submit-fixed = f.submit "更新"

app/views/users/_user_list.slim
- users.each do |user|
  div.card_user
    = link_to user_path(user), class: 'image' do
      = attachment_image_tag user, :profile_image, fallback: 'no-image.png'
    .profile 
      = link_to user.username,  user_path(user), class:'user_name'
      p.recipe_count
        | 投稿数： 
        = user.recipes.length
    - if current_user != nil
      - if user != current_user
        -if current_user.following?(user)
          = button_to "フォロー解除", user_relationships_path(user.id), method: :delete
        -else
          = button_to "フォローする", user_relationships_path(user.id), method: :post

app/views/users/edit.html.slim
.center_container
  h1.page_title
    | ユーザー編集
  - if @user.errors.any?
    .notification.is-danger
      h2 = pluralize(@user.errors.count,'error')
      ul 
        - @user.errors.full_messages.each do |message|
          li = message
        end 

  == render 'form'
  

app/views/users/index.html.slim
h1.page_title
  | レシピグラマー一覧
.users_index.center_container
  .user_list
    == render 'user_list', users: @users

app/views/users/show.html.slim
.center_container
  h1.page_title
    | マイページ
  .user_profile_content
    = attachment_image_tag @user, :profile_image, fallback: 'no-image.png', class: "profile_image is-rounded"
    .profile
      .top_profile
        p.user_name = @user.username
        - if current_user != nil
          - if @user == current_user
            p.user_email= @user.email
            td
              = link_to "編集", edit_user_path(@user)
          - else
            - if current_user.following?(@user)
              = button_to "フォロー解除", user_relationships_path(@user.id), method: :delete
            - else
              = button_to "フォローする", user_relationships_path(@user.id), method: :post
      .follow_folloed
        = link_to "#{@user.followings.count}フォロー", user_followings_path(@user.id)
        = link_to "#{@user.followers.count}フォロワー", user_followers_path(@user.id)
      .profile = simple_format @user.profile
  .container_recipe
    - if @user.fixed_recipe != nil
      p 固定ツイート
      == render 'recipes/recipe_card', recipe: @user.fixed_recipe, isFixed: true
    == render 'recipes/recipe_list', recipes: @recipes