config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: 'recipes#index'
  resources :users do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes do
    resource :favorite, only: %i[create destroy]
    resource :comment, only: %i[create destroy show]
    get 'like' => 'favorites#favousers', as: 'users'
  end
  post 'change_index', to: 'recipes#'
  post 'fixed_recipe', to: 'recipes#'
  post 'un_fixed_recipe', to:'recipes#'

  get 'hashtags', to: 'hashtags#show'
  get 'hashtags/:hashtag', to: 'hashtags#show', as: 'search_route'
  post 'hashtags/', to: 'hashtags#search', as: 'search_post_route'
  resources :notifications, only: :index
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Recipegram
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_importmap_tags
  body
    div.style
      div.nav-layer
      div.nav-bar
        = link_to root_path, class: "nav-bar-item" do
          h1.title.is-4[style="font-family: cursive;"]
            | Recipegram
        = link_to change_index_path(display_index: session[:home_display_index]), method: :post, class: "nav-bar-item button" do
          .menu-svg= image_tag 'mainMenu/home.svg', inline: true
          span ホーム
        = link_to hashtags_path, class: "nav-bar-item button" do 
          .menu-svg= image_tag 'mainMenu/search.svg', inline: true
          span レシピ検索
        = link_to notifications_path, class: "nav-bar-item button" do 
          .menu-svg= image_tag 'mainMenu/notification.svg', inline: true
          span 通知
        /= link_to "レシピグラマー一覧", users_path, class: "nav-bar-item button" 
        - if user_signed_in?
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-bar-item button"
          = link_to user_path(current_user.id), class: "nav-bar-item button" do
            .menu-svg= image_tag 'mainMenu/user.svg', inline: true
            span プロフィール
          = link_to new_recipe_path, class: "nav-bar-item button" do 
            .menu-svg= image_tag 'mainMenu/post.svg', inline: true
            span 新規投稿
        - else
          = link_to "ログイン", new_user_session_path, class: "nav-bar-item button"
          = link_to "新規登録", new_user_registration_path, class: "nav-bar-item button"
      div.main
        = yield

javascript:
  $(".nav-bar").width($(".nav-layer").width());
  let $sideElement = $(".side-element");
  let isScroll = false;
  if(window.innerHeight < $sideElement.height()){
    $sideElement.removeClass("no-scroll");
    $sideElement.addClass("scroll");
    isScroll = true;
  } else {
    $sideElement.removeClass("scroll");
    $sideElement.addClass("no-scroll");
    isScroll = false;
  }

  $(window).resize(function(event) {
    $(".nav-bar").width($(".nav-layer").width());
    let $sideElement = $(".side-element");
    if(window.innerHeight < $sideElement.height()) {
      $sideElement.removeClass("no-scroll");
      $sideElement.addClass("scroll");
      isScroll = true;
    } else {
      $sideElement.removeClass("scroll");
      $sideElement.addClass("no-scroll");
      isScroll = false;
    }
  });

  let lastScrollPos = 0;
  let down = false;
  let marginTop = 0
  $(window).on("scroll", function() {
    if(isScroll) {
      const currentScrollPos = $(this).scrollTop();
      let $scrollElement = $(".scroll");
      let $topMargin = $(".top-margin");
      if(lastScrollPos < currentScrollPos) {
        if(!down) {
          $scrollElement.css({top:"-120px",bottom:""});
          if(currentScrollPos < marginTop) {
            marginTop = currentScrollPos + 60
            $topMargin.css({"margin-top": marginTop});
          }
        }
        down = true;
      } else {
        if(down) {
          if(currentScrollPos < 120) {
            $topMargin.css({"margin-top": 120});
            marginTop = 120
          } else if(currentScrollPos - marginTop > 120) {
            marginTop = currentScrollPos - 120;
          }
            $topMargin.css({"margin-top": marginTop});
          $scrollElement.css({top:"",bottom:"-120px"});
        }
        down = false;
      }
      lastScrollPos = currentScrollPos;
    }
  })